version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - run: exit 0
#      - checkout
#      - restore_cache:
#          keys:
#            - composer-v1-{{ checksum "composer.lock" }}
#      - run:
#          name: composer install
#          command: composer install --prefer-dist
#      - save_cache:
#          key: composer-v1-{{ checksum "composer.lock" }}
#          paths:
#            - vendor
#      - restore_cache:
#          key: npm-v1-{{ checksum "package-lock.json" }}
#      - run:
#          name: npm ci
#          command: |
#            if [ ! -d node_modules ]; then
#              npm ci
#            fi
#      - save_cache:
#          key: npm-v1-{{ checksum "package-lock.json" }}
#          paths:
#            - node_modules
#      - run:
#          name: npm run dev
#          command: npm rum dev
#      - run:
#          name: php test
#          command: ./vendor/bin/phpunit

  deploy:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - c3:c0:b3:44:c1:0a:4c:2a:75:75:f7:d9:50:9e:7f:de
      - run:
          name: deploy
          command: |
            echo -e "Host git-codecommit.*.amazonaws.com\n  User ${AWS_CODE_COMMIT_SSH_KEY_ID}\n  StrictHostKeyChecking no" > ${HOME}/.ssh/config
            git push ssh://git-codecommit.ap-northeast-1.amazonaws.com/v1/repos/laravel-ci feature/codecommit_deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - feature/codecommit_deploy
