version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
      - image: circleci/postgres:10.1
        environment:
          POSTGRES_USER: default
          POSTGRES_PASSWORD: secret
    environment:
      APP_ENV: testing
      DB_HOST: localhost
      DB_PORT: 5432
    steps:
      - checkout
      - run:
          name: composer install
          command: composer install --prefer-dist
      - run:
          name: npm ci
          command: npm ci
      - run:
          name: npm run dev
          command: npm rum dev
      - run:
          name: php test
          command: ./vendor/bin/phpunit
