version: 2.1
orbs:
  aws-code-deploy: circleci/aws-code-deploy@1.0
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
      - run:
          name: composer install
          command: composer install --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
      - run:
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: npm run dev
          command: npm rum dev
      - run:
          name: php test
          command: ./vendor/bin/phpunit

  deploy:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: deploy
          command: |
            echo -e "Host git-codecommit.*.amazonaws.com\n  User ${AWS_CODE_COMMIT_SSH_KEY_ID}\n  StrictHostKeyChecking no" > ${HOME}/.ssh/config
            git push ssh://git-codecommit.ap-northeast-1.amazonaws.com/v1/repos/laravel-ci master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - aws-code-deploy/deploy:
          application-name: laravel-ci
          bundle-bucket: codedeploy-ap-northeast-1-458821178073
          bundle-key: laravel-ci
          deployment-group: laravel-ci-s3
          service-role-arn: arn:aws:iam::878623936393:role/CodeDeployRole
          requires:
            - build
          filters:
            branches:
              only:
                - master
