version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - run:
          name: composer install
          command: composer install --prefer-dist
      - run:
          name: npm ci
          command: npm ci
      - run:
          name: npm run dev
          command: npm rum dev
      - run:
          name: php test
          command: ./vendor/bin/phpunit
