version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
      - image: circleci/postgres:10.1
        environment:
          POSTGRES_DB: larasns
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
    environment:
      APP_ENV: testing
      DB_HOST: localhost
      DB_PORT: 5432
    steps:
      - checkout
      - run:
          name: composer install
          command: composer install --prefer-dist
      - run:
          name: wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: wait for db
          command: sleep 60
      - run:
          name: php test
          command: ./vendor/bin/phpunit
