version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
      - run:
          name: composer install
          command: composer install --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
      - run:
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: npm run dev
          command: npm rum dev
      - run:
          name: php test
          command: ./vendor/bin/phpunit

  deploy:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - run:
          name: build for production
          command : |
            - composer install --no-dev --prefer-dist
            - npm ci
            - npm run prod
            - zip -ryq laravel-ci.zip
#      - add_ssh_keys
#      - run:
#          name: deploy
#          command: |
#            echo -e "Host git-codecommit.*.amazonaws.com\n  User ${AWS_CODE_COMMIT_SSH_KEY_ID}\n  StrictHostKeyChecking no" > ${HOME}/.ssh/config
#            git push ssh://git-codecommit.ap-northeast-1.amazonaws.com/v1/repos/laravel-ci master
      - aws-s3/copy:
          from: laravel-ci.zip
          to: s3://codedeploy-ap-northeast-1-458821178073

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - master
